# Generated by Django 4.2.6 on 2023-10-27 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_django_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile1',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile1',
            name='technology',
        ),
        migrations.AddField(
            model_name='userprofile1',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile1',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile1',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
